from __future__ import annotations

import datetime as dt
import random

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.db import get_db
from app.models import Trigger, Worker, Policy
from app.routes.common import get_current_user
from app.schemas import TriggerHistoryItem, TriggerLiveItem


router = APIRouter(prefix="/api/triggers", tags=["triggers"])


TRIGGERS = [
    {
        "type": "Heavy Rainfall",
        "trigger_type": "Heavy Rainfall",
        "threshold": "> 50mm/hr",
        "data_source": "IMD API",
    },
    {
        "type": "Severe AQI Spike",
        "trigger_type": "Severe AQI Spike",
        "threshold": "AQI > 300 (Severe+)",
        "data_source": "CPCB National API",
    },
    {
        "type": "Flood Alert",
        "trigger_type": "Flood Alert",
        "threshold": "NDMA Red Alert",
        "data_source": "IMD + NDMA",
    },
    {
        "type": "Administrative Curfew",
        "trigger_type": "Administrative Curfew",
        "threshold": "Govt advisory active",
        "data_source": "State Govt / Police",
    },
    {
        "type": "City-wide Strike",
        "trigger_type": "City-wide Strike",
        "threshold": "Traffic drop > 70%",
        "data_source": "Traffic + News APIs",
    },
    {
        "type": "Extreme Heat Wave",
        "trigger_type": "Extreme Heat Wave",
        "threshold": "Temp > 42C (IMD, 12-4pm)",
        "data_source": "IMD Heat Advisory",
    },
]


def _mock_actual(trigger_type: str) -> tuple[float | None, str]:
    # Return (actual_value, status_label)
    roll = random.random()
    if trigger_type == "Heavy Rainfall":
        actual = 30 + roll * 90  # 30..120 mm/hr
        return round(actual, 1), "PAYOUT" if actual > 50 else "MONITORING"
    if trigger_type == "Severe AQI Spike":
        actual = 120 + roll * 420
        return round(actual, 0), "PAYOUT" if actual > 300 else "MONITORING"
    if trigger_type == "Flood Alert":
        actual = 0.0
        return None, "PAYOUT" if roll > 0.55 else "MONITORING"
    if trigger_type == "Administrative Curfew":
        return None, "ACTIVE" if roll > 0.6 else "MONITORING"
    if trigger_type == "City-wide Strike":
        actual = 40 + roll * 60  # traffic drop %
        return round(actual, 0), "PAYOUT" if actual > 70 else "MONITORING"
    if trigger_type == "Extreme Heat Wave":
        actual = 34 + roll * 18  # temp
        return round(actual, 1), "PAYOUT" if actual > 42 else "MONITORING"
    return None, "MONITORING"


def _maybe_clear_old_triggers(db: Session, zone: str) -> None:
    cutoff = dt.datetime.utcnow() - dt.timedelta(minutes=15)
    old_active = db.query(Trigger).filter(Trigger.zone == zone, Trigger.status != "CLEAR", Trigger.fired_at < cutoff).all()
    for t in old_active:
        t.status = "CLEAR"
        t.cleared_at = dt.datetime.utcnow()
    if old_active:
        db.commit()


@router.get("/live", response_model=list[TriggerLiveItem])
def live_triggers(current: Worker = Depends(get_current_user), db: Session = Depends(get_db)):
    # Prototype-friendly: ensure there is at least one feed item if triggers aren't being generated by celery yet.
    _maybe_clear_old_triggers(db, current.zone)

    existing = (
        db.query(Trigger)
        .filter(Trigger.zone == current.zone, Trigger.city == current.city, Trigger.status != "CLEAR")
        .order_by(Trigger.fired_at.desc())
        .limit(6)
        .all()
    )

    if len(existing) == 0:
        # Only create if worker has an active policy (keeps the demo coherent).
        active_policy = (
            db.query(Policy)
            .filter(Policy.worker_id == current.id, Policy.status == "active")
            .order_by(Policy.start_date.desc())
            .first()
        )
        if active_policy:
            # Create 1-2 triggers for the selected zone.
            for item in random.sample(TRIGGERS, k=random.randint(1, 2)):
                actual_value, status = _mock_actual(item["trigger_type"])
                db.add(
                    Trigger(
                        trigger_type=item["trigger_type"],
                        zone=current.zone,
                        city=current.city,
                        severity="high",
                        threshold=item["threshold"],
                        actual_value=actual_value,
                        data_source=item["data_source"],
                        status=status,
                        fired_at=dt.datetime.utcnow(),
                    )
                )
            db.commit()
            existing = (
                db.query(Trigger)
                .filter(Trigger.zone == current.zone, Trigger.city == current.city, Trigger.status != "CLEAR")
                .order_by(Trigger.fired_at.desc())
                .limit(6)
                .all()
            )

    return [
        TriggerLiveItem(
            id=t.id,
            type=t.trigger_type,
            status=t.status,
            dataSource=t.data_source,
            threshold=t.threshold,
            actualValue=t.actual_value,
        )
        for t in existing
    ]


@router.get("/history", response_model=list[TriggerHistoryItem])
def history_triggers(current: Worker = Depends(get_current_user), db: Session = Depends(get_db)):
    since = dt.datetime.utcnow() - dt.timedelta(days=30)
    items = (
        db.query(Trigger)
        .filter(Trigger.zone == current.zone, Trigger.city == current.city, Trigger.fired_at >= since)
        .order_by(Trigger.fired_at.desc())
        .limit(40)
        .all()
    )
    return [
        TriggerHistoryItem(
            id=t.id,
            type=t.trigger_type,
            firedAt=t.fired_at,
            actualValue=t.actual_value,
            status=t.status,
        )
        for t in items
    ]

